import { relative } from "node:path";
import { type LearnConfig, dashboardPath } from "./config.ts";
import { conceptStats, readLedger } from "./ledger.ts";
import type { DueTopic } from "./scheduler.ts";
import { actionable, dueTopics } from "./topics.ts";
import { today, writeNote } from "./vault.ts";

export function wikilink(config: LearnConfig, path: string, label: string): string {
  const rel = relative(config.vault, path).replace(/\.md$/, "");
  return `[[${rel}|${label}]]`;
}

/** Human phrasing for how overdue a topic is. */
export function describeDue(entry: DueTopic): string {
  if (entry.status === "never") {
    const age = entry.daysSinceQuiz;
    return age === null ? "never quizzed" : `never quizzed (${age}d old)`;
  }
  if (entry.status === "overdue") return `${entry.overdueDays}d overdue`;
  if (entry.status === "due") return "due today";
  return `in ${-entry.overdueDays}d`;
}

export function summarizeDue(topics: DueTopic[]): string {
  const live = actionable(topics);
  if (live.length === 0) return "Nothing due.";
  const parts: string[] = [];
  const overdue = live.filter((entry) => entry.status === "overdue");
  if (overdue.length > 0) {
    const worst = Math.max(...overdue.map((entry) => entry.overdueDays));
    parts.push(`${overdue.length} overdue (worst ${worst}d)`);
  }
  const due = live.filter((entry) => entry.status === "due");
  if (due.length > 0) parts.push(`${due.length} due today`);
  const never = live.filter((entry) => entry.status === "never");
  if (never.length > 0) parts.push(`${never.length} never quizzed`);
  return parts.join(" · ");
}

export function renderDashboard(config: LearnConfig): string {
  const topics = dueTopics(config);
  const weak = conceptStats(readLedger(config)).filter(
    (entry) => entry.attempts >= 2 && entry.weakness > 0.3,
  );

  const section = (title: string, rows: string[]) =>
    rows.length === 0 ? "" : `## ${title}\n\n${rows.join("\n")}\n`;

  const row = (entry: DueTopic) =>
    `- ${wikilink(config, entry.path, entry.title)} — ${describeDue(entry)}` +
    (entry.state.mastery > 0 ? ` · mastery ${Math.round(entry.state.mastery * 100)}%` : "") +
    (entry.cold ? " · **cold, re-teach before quizzing**" : "");

  const byStatus = (status: DueTopic["status"]) =>
    topics.filter((entry) => entry.status === status).map(row);

  return [
    "---",
    "type: dashboard",
    `updated: ${today()}`,
    "tags:",
    "  - learning/dashboard",
    "---",
    "",
    "# Learning dashboard",
    "",
    `> [!abstract] ${summarizeDue(topics)}`,
    "> `/recall` runs what is due · `/checkpoint <topic>` after a chapter · `/gaps` for the weak list",
    "",
    section("Overdue", byStatus("overdue")),
    section("Due today", byStatus("due")),
    section("Never quizzed", byStatus("never")),
    section("Upcoming", byStatus("upcoming")),
    section(
      "Weakest concepts",
      weak
        .slice(0, 10)
        .map(
          (entry) =>
            `- \`${entry.concept}\` — ${Math.round(entry.accuracy * 100)}% over ${entry.attempts} attempts, last tested ${entry.lastSeen}`,
        ),
    ),
    "---",
    "",
    "_Generated by the `learn` extension — edits here are overwritten._",
    "",
  ]
    .filter((chunk) => chunk !== "")
    .join("\n");
}

export function writeDashboard(config: LearnConfig): string {
  const path = dashboardPath(config);
  writeNote(path, renderDashboard(config));
  return path;
}
